#!/usr/bin/env node
/**
 * Generates public/precache.js: the exact list of files the service worker
 * should download on install, plus a version hash of their contents.
 *
 * Because the list is generated from the real tree, adding a widget or a
 * chapter can never silently leave it out of the offline cache. The version
 * is a hash of every file's bytes, so a single character change invalidates
 * the old cache and nothing else does.
 *
 * Run with: npm run sw
 *
 * With --check it writes nothing and exits non-zero if the committed file is
 * out of date. That check deliberately compares generated text against the
 * file on disk rather than shelling out to `git diff`, so it works the same
 * in CI, in a deploy build with a shallow clone, and on a developer's machine.
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PUBLIC = path.join(ROOT, 'public');

/** Files that must never be precached. */
const SKIP = new Set(['sw.js', 'precache.js']);
const EXT = new Set(['.html', '.js', '.css', '.webmanifest', '.png', '.svg', '.json', '.woff2']);

function walk(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

const files = walk(PUBLIC)
  .filter((f) => EXT.has(path.extname(f).toLowerCase()))
  .filter((f) => !SKIP.has(path.relative(PUBLIC, f).replace(/\\/g, '/')))
  .sort();

const hash = crypto.createHash('sha256');
for (const f of files) hash.update(fs.readFileSync(f));
const version = hash.digest('hex').slice(0, 10);

const urls = files.map((f) => './' + path.relative(PUBLIC, f).replace(/\\/g, '/'));

const out = `/* GENERATED by tools/build-sw.js - do not edit by hand. */
self.__PRECACHE_VERSION = ${JSON.stringify(version)};
self.__PRECACHE = ${JSON.stringify(urls, null, 2)};
`;

const target = path.join(PUBLIC, 'precache.js');
const bytes = files.reduce((n, f) => n + fs.statSync(f).size, 0);

if (process.argv.includes('--check')) {
  const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
  // Normalise line endings before comparing: a Windows checkout may hold CRLF
  // even though .gitattributes stores LF, and that is not a staleness problem.
  const norm = (s) => s.replace(/\r\n/g, '\n');
  if (norm(current) !== norm(out)) {
    console.error('\n  ✗ public/precache.js is stale.');
    console.error('    public/ has changed since it was last generated, so the');
    console.error('    service worker would precache the wrong files offline.');
    console.error('\n    Fix it with:  npm run sw\n');
    process.exit(1);
  }
  console.log(`  ✓ precache.js is current · ${urls.length} files · version ${version}`);
  process.exit(0);
}

fs.writeFileSync(target, out);
console.log(`  precache.js written`);
console.log(`  ${urls.length} files · ${(bytes / 1024).toFixed(0)} KB · version ${version}`);
